version: "3"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:8.0.5
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ../target/exporter/zeebe-hazelcast-exporter.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network

  zeeqs-in-memory:
    container_name: zeeqs-in-memory
    image: ghcr.io/camunda-community-hub/zeeqs:2.4.0
    environment:
      - zeebe.client.broker.gateway-address=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    ports:
      - "9000:9000"
    depends_on:
      - zeebe
    networks:
      - zeebe_network
    profiles:
      - in-memory

  zeeqs-postgres:
    container_name: zeeqs-postgres
    image: ghcr.io/camunda-community-hub/zeeqs:2.4.0
    environment:
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
      - spring.datasource.url=jdbc:postgresql://postgres-zeeqs:5432/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=zeebe
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.hibernate.ddl-auto=create
    ports:
      - "9000:9000"
    depends_on:
      - zeebe
      - postgres-zeeqs
    networks:
      - zeebe_network
    profiles:
      - postgres

  postgres-zeeqs:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: zeebe
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - zeebe_network
    profiles:
      - postgres

volumes:
  database-data:
    driver: local